import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Experiência Profissional</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h2 style={{color:'snow', marginBottom: '30px'}}>Experiência Profissional</h2>
      <div className={styles.grid}>
        <div className={styles.card}>
            <h2>Desenvolvedor C#</h2>
            <p>Portal do Médico</p>
            <br/>
            <p style={{color: 'white'}}>
            Durante a oportunidade atuei com o desenvolvimento de aplicações em C# Asp.Net,
            SQL Server, Unit Tests e refatoração de códigos visando a otimização da performance
            da aplicação, MVC, Web API, SQL Server, Design Pattern, integração de APIs tais como
            anymarket, smartsup, além de aprimoramentos na plataforma do marketplace.
            </p>
            <br/>
            <p>Dezembro de 2022 a Março de 2023</p>
        </div>
        <div className={styles.card}>
            <h2>Desenvolvedor C#</h2>
            <p>EasyComtec</p>
            <br/>
            <p className={styles.card.p}>
            Durante a oportunidade atuei com o desenvolvimento de aplicações em C# Asp.Net, SQL Server,
            Angular, Azure Functions, Unit Tests e refatoração de códigos, MVC, Web API, SQL Server,
            Unit Of Work Design Pattern.
            </p>
            <br/>
            <p>Junho de 2022 a Outubro de 2022</p>
        </div>
        <div className={styles.card}>
            <h2>Sistema de Gestão ERP Estágio C#</h2>
            <p>Soditech</p>
            <br/>
            <p>
            Experiência em estagio na qual foi recebido o desafio de desenvolver um aplicativo na linguagem C#
            Asp.Net e SQL Server para a gestão interna da empresa, utilizando meios de extração de dados do
            antigo site da empresa através de webhook e webCrawling.
            </p>
            <br/>
            <p>Março de 2022 a Junho de 2022</p>
        </div>
        <div className={styles.card}>
            <h2>Desenvolvedor C#</h2>
            <p>Unibrasil</p>
            <br/>
            <p>
            Expêriencia na qual o desafio principal foi o desenvolvimento de um sistema de bilheteria
            eletrônica em C#, Windows Forms e SQL Server.
            </p>
            <br/>
            <p>Setembro de 2021 a Janeiro de 2022</p>
        </div>
        <div className={styles.card}>
            <h2>Desenvolvedor C#</h2>
            <p>Unibrasil</p>
            <br/>
            <p>
            Experiência na qual foi recebido o desafio de desenvolver um sistema de gestão e controle
            de doadores de sangue em uma clinica hospitalar, na linguagem de programação C# Web com blazor
            framework e SQL Server e Aws Cloud.
            </p>
            <br/>
            <p>Março de 2021 a Setembro de 2021</p>
        </div>
        <div className={styles.card}>
            <h2>Desenvolvedor C#</h2>
            <p>SGAmbiental</p>
            <br/>
            <p>
            Experiência na qual foi desenvolvida uma site de gestão ambiental e controle de agenda de clientes
            em C#, AWS Cloud, e SQL Server.
            </p>
            <br/>
            <p>Agosto de 2020 a Agosto de 2021</p>
        </div>
        </div>
      </main>
    </>
  )
}
