import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h2>Sobre Raphael</h2>
        <div className={styles.card}>
            <p style={{width:'300px'}} className='font-bold'>
            Jovem ambicioso atualmente com 24 anos de idade, estudante de Análise e Desenvolvimento de Sistemas,
            apaixonado por tecnologia desde cedo, programador C# voltado para o Asp.net,
            .Net core, utilizando os padrões de design MVC e Unit of Work, desenvolvendo funcionalidades
            através do Test driven development utilizando o framework Moq. Atuo no desenvolvimento de softwares
            Asp.Net através do Entity Framework e bancos de dados relacionais e não relacionais, além de criar
            apps em ReactJs consumindo WebApi Rest C# com Swagger, integração de apis de pagamento como PayPal
            e mercado pago. Desenvolvimento em cloud como AWS, azure e Firebase.
            </p>
            <br/>
        </div>
        </main>
    </>
  )
}
